# Generated by Django 3.2.4 on 2021-06-07 04:44

import ProductApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200, validators=[ProductApp.models.nameFiledValidator])),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.brands')),
            ],
        ),
    ]
