# Generated by Django 3.1.12 on 2021-07-03 15:01

import ProductApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_alter_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, validators=[ProductApp.models.nameFiledValidator])),
                ('product', models.ManyToManyField(related_name='prdcts', to='ProductApp.products')),
            ],
        ),
    ]
